### ISSUE TITLE
Get higlass to work as a component in a larger app

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/cTracks#1]
We want to load higlass as a library that we can then interface with.

**Comment by pkerpedjiev** [comment]
Did this ever get resolved? 

I added documentation for how it can be done here:

https://hms-dbmi.github.io/higlass-docs/higlass_client.html#higlass-api

**Comment by mildewey** [comment]
Higlass is now loaded as a component in cTracks. cTracks, however, is a stand-alone app that can be externally controlled by other browser contexts with the same origin.
