### ISSUE TITLE
Epic: A full genome chart for 1-10(?) patients will be displayed in one chart

### ISSUE THREAD

**Issue by richkingsford** [visdesignlab/cTracks#10]
![image](https://user-images.githubusercontent.com/6001402/30559599-64914f40-9c72-11e7-8fb9-6976b75e3b8d.png)
•	Default chart is zoomed out to view full genome but zoomable to high detail

•	Each track will be clearly labeled by sample name and track type

•	Includes tracks
  o	transcript track
  o	ROI Track for specific panel
  o	CNV calls track
  o	Log2 ratios track

•	User can change order, size, colors (using existing Higlass controls)
•	interactive zoom handles change detail view panes zoom (using existing Higlass controls)
•	Y axis scales will be displayed
•	Y axis scales will be adjustable
•	User can click to jump between full genome or a specific chr view

•	Nice to have
  o	Vertical divider bars will separate chromosomes
  o	User has option to collapse large non-covered regions of genome with clearly marked collapse boundaries
  o	(Punt) User can search and display cohort of samples
  o	(Punt) chromosomal bands track displayed in full genome chart (idogram of banding pattern in chromosomes)

**Comment by durtschi** [comment]
Looks like this was addressed by the layout and flexibility that SCI added.
