### ISSUE TITLE
Epic: A detailed chart for 1-5(?) patients and custom tracks will be displayed

### ISSUE THREAD

**Issue by richkingsford** [visdesignlab/cTracks#11]
![image](https://user-images.githubusercontent.com/6001402/30560630-c244c416-9c75-11e7-9946-ee0c96e25144.png)
![image](https://user-images.githubusercontent.com/6001402/30560634-c40411e4-9c75-11e7-9bf3-2c6f09d279f1.png)

•	User sets view region by selection of region in full genome chart
•	In zoomed out views, scatter data is subsampled
o	Subsampled scatter points will be selected based on importance (Jacob to determine if clodius has this ability)
o	Importance will be defined as distance from mean or distance from neighbor. (Jacob will compute importance. Jacob will add importance column to data bed files if needed)

•	Log2 rolling average track (display as line) will be displayed (Jacob will provide rolling average track)
•	Zoomable

•	Default view will be only tracks from primary sample
o	Transcript track
o	ROI Track for specific panel
o	CNV calls
o	Log2
o	Log2 rolling average
o	B-allele frequency
o	LOH suspected regions
o	Quality scores
o	Absolute read depth

•	User can choose to add any track from any primary or background sample from dropdown menu
•	Each track will be clearly labeled by sample name and track type
•	Max and min limit lines can be displayed on at least these track types and User can adjust limit values from menu (or equivalent)
o	CNV calls
o	Log2
o	Log2 rolling average

•	User can change order, size, colors of tracks

•	Nice to have
o	Log2 rolling average track will be overlaid on the Log2 chart with distinguishing color
o	hover/right click on log2, B-allele data shows local data values (if zoomed in far enough to see individual points)
o	historical ARUP CNV histogram track(s) will be available for display in chart (Jacob will provide tracks)
o	(Punt) Users can upload bed file formatted data tracks for storage and display (Separate Epic?)
o	(Punt) Log2 track baselines can be set by user (i.e., y axis can be shifted up or down by user, independent of data)
o	(Punt) User check box for each variant indicating that it has been reviewed is present in table (status saved in NGSWeb)
o	(Punt) A note field for each variant is present in table (contents saved in NGSWeb)
o	(Punt) Rolling standard deviations, box and whisker, or quartile lines till later version (Users may not see usefulness right now)

**Comment by durtschi** [comment]
Most of this was addressed in the MVP. Some other items will be addressed in NGSWeb. An new issue for a rolling average track will be added here.
