### ISSUE TITLE
Epic: Data Export and External links

### ISSUE THREAD

**Issue by richkingsford** [visdesignlab/cTracks#13]
•	Log2 bed file can be exported to local bed format files from menu (or equivalent) using tab-delimited CSV file
•	A link to IGV of same chart region will be available (IGV must already be opened on User computer)

Must-have for clinical application for germline, not so much for oncology.

**Comment by durtschi** [comment]
Looks like this is an NGSWeb issue. A download button for the Log2 data file should be added to NGSWeb as well as a link to NGSWeb.
