### ISSUE TITLE
Increase data point density in tracks

### ISSUE THREAD

**Issue by durtschi** [visdesignlab/cTracks#25]
This would give a more familiar look to the users but may cause app to run slow. It would be nice to try.

From a subsequent conversation:

"What I think I expect to see are more points along the vertical axis to indicate better the distribution of values. Instead of one averaged value, perhaps a few different values. It seamed that packing more tiles in the same space could be one way of doing that. A better solution may be the idea we have discussed of displaying multiple values for each region. This could be quantile values along with max or min."

![pasted image at 2017_12_12 10_46 am](https://user-images.githubusercontent.com/2143629/33900476-809c0c68-df3c-11e7-87df-9d16ecb45a83.png)

**Comment by mildewey** [comment]
This is now resolved for bigwig files by the whisker and range plot options.
