### ISSUE TITLE
Need fix so that data point limits stay accurate between zooms

### ISSUE THREAD

**Issue by durtschi** [visdesignlab/cTracks#31]
Data limits appear do not appear to stay accurate between zooms. The chromosome position min and max for a data point (or grouped data points) should always match the position min and max of all combined points

**Comment by pkerpedjiev** [comment]
This is actually a "feature" :)

The data are currently scaled according to the visible region. There is an issue to change this in the higlass repository: https://github.com/hms-dbmi/higlass/issues/171

**Comment by durtschi** [comment]
Thanks for the clarification, Peter. Do you expect a week, month, or year order of magnitude timeline for this change?

**Comment by pkerpedjiev** [comment]
A month or two. It's one of the highest priority issues in HiGlass at the moment so as soon as I get a chance to swing around to fixing things I'll focus on that.

**Comment by mildewey** [comment]
Users can now fix the y-axis in the cTracks interface.
