### ISSUE TITLE
Add windowing function "mean plus whiskers" as display option for bigwig data

### ISSUE THREAD

**Issue by durtschi** [visdesignlab/cTracks#34]
For CNV depth data in a "zoomed-out" view, it is important to see extreme values as well as the mean/stdev for each window. I was shocked to find a nice way to do this in the UCSC genome browser. It is defined as:
"Mean+whiskers" - displays the mean in a dark shade, one standard deviation around the mean in a medium shade, and the maximum/minimum in a light shade. For bar graphs only the mean, the mean plus a standard deviation, and the max are visible. This mode is not available if the Overlay method is stacked.

Data needed for this display is baked into the bigwig file format (for each zoom level, mean, min, max, sum, sum of squares is included)

I think this requires a change to higlass.

**Comment by durtschi** [comment]
![image](https://user-images.githubusercontent.com/1211648/44465380-9cfbc780-a5da-11e8-9f7a-c16217606374.png

**Comment by mildewey** [comment]
Resolved in latest master.
