### ISSUE TITLE
Develop some NGS.web wireframes and get stakeholder feedback

### ISSUE THREAD

**Issue by richkingsford** [visdesignlab/cTracks#6]
Check out [CNV Visualization Mockups.pdf](https://github.com/visdesignlab/copy-number/files/1311608/CNV.Visualization.Mockups.pdf)

Suggest we as a dev team discuss + reiterate and then we show it to stakeholders.

**Comment by durtschi** [comment]
With a current working prototype, this seems to be completed. There may be some desire to show Boardwalk improvements or NGSWeb wireframes.
