### ISSUE TITLE
Epic: CNV Visualization tool will start up with specific samples loaded

### ISSUE THREAD

**Issue by richkingsford** [visdesignlab/cTracks#8]
User stories:
•	From the NGSWeb sample variant table page, the user can click a button that launches the CNV visualization page
•	Sample in NGSWeb is passed to tool and becomes primary sample in tool
•	A set of predefined background samples will be passed from NGSWeb to tool and will also load as secondary (i.e., reference) samples
•	All tracks for primary and reference samples will be present in the “add track” dropdown menu in the tool
•	User specific settings are saved as json on local machine with button (or menu) click
•	Nice to have
o	User specific config settings saved in NGSWeb (saved based on user and test type)
o	NGSWeb will have a field (or button with popup field, or equivalent) on the variant table page of the primary sample to enter accession number of additional samples that will be passed to tool. The tool will update the “add track” dropdown menu to include all tracks for the new sample

**Comment by durtschi** [comment]
The framework for this appears to be in the MVP cTracks version. NGSWeb needs to implement.
