### ISSUE TITLE
Epic: Charts will all be arranged in one (or more?) browser tabs

### ISSUE THREAD

**Issue by richkingsford** [visdesignlab/cTracks#9]
![image](https://user-images.githubusercontent.com/6001402/30559544-3d6622a6-9c72-11e7-9e1f-fc4e7f2570ea.png)

User stories:
•	A genome chart will be placed at the top of the page
•	Detail chart will be placed below the genome chart
•	The page length grows as user adds more samples
•	The page length changes as users manually stretch the height of tracks

**Comment by durtschi** [comment]
Just wanted to let you know. The “nice to have” items are things that need followup and won’t make it into the MVP unless warranted. You probably don’t want to make issues for any of those. We should discuss.

**Comment by durtschi** [comment]
Nice to have
• Split screen view can be started by user (how?) with tracks one screen and table on second screen.

**Comment by durtschi** [comment]
MVP now includes all of the user story point. I'll add another issue for the "nice to have" split screen.
